version: '3.1'

services:
  db:
    image: postgres
    restart: always
    user: postgres
    env_file:
      - .env.dev
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    restart:
      unless-stopped
    ports:
      - 3000:80
    depends_on:
      - db
    volumes:
      - ./backend/:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./backend/.env.dev
    command: /bin/bash -c "yarn && yarn dev"

volumes:
  db:
